### ISSUE TITLE
Run easily from new project

### ISSUE THREAD

**Issue by derekbounce** [bouncelab/resolver-generator#1]
Right now you have to manually copy all the files in this repo to your project before you can run it.

Also if the generator code changes, you have to manually re-import.

**Comment by stefangomez** [comment]
does python have global scripts like nodejs does? it'd be super nice to have a CLI that's like `npm install blabcodegen -g` that installs the script globally

**Comment by derekbounce** [comment]
Created shell script that downloads and runs latest version of tool. Installation instructions in README
